"""Add user_type and specialties

Revision ID: f87b2ce17b16
Revises: 2704d3cba4a3
Create Date: 2025-09-03 22:56:31.846077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87b2ce17b16'
down_revision: Union[str, Sequence[str], None] = '2704d3cba4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('custom_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_specialties_id'), 'user_specialties', ['id'], unique=False)
    op.add_column('users', sa.Column('user_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('unit_preference', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unit_preference')
    op.drop_column('users', 'user_type')
    op.drop_index(op.f('ix_user_specialties_id'), table_name='user_specialties')
    op.drop_table('user_specialties')
    # ### end Alembic commands ###
